export const ProjectItems = {
    project: [
      "AD Bank",
      "Ajman Majlis",
      "Al Waleed Paradise",
      "Al Wazzan",
      "Aprtment",
      "Art Center",
      "Belresheed Dubai Office",
      "Belresheed Sharjah Office",
      "Fitness First",
      "Gents Saloon",
      "Hamil Al Musk Shop",
      "Jumeriah Villa",
      "KSA Villa",
      "Medical Center",
      "Moroccan Project",
      "Osama Villa",
      "Panama DCC",
      "Party 21 Sahara",
      "Project 3",
      "Project 5",
      "Project 6",
      "Project 7",
      "Project 8",
      "Project 9",
      "Thamina Villa",
      "villa Barsha South"
    ],
    main: [
      "/static/images/ADBank/Bank_View01.jpg",
      "/static/images/AjmanMajlis/45.JPG",
      "/static/images/AlWaleedParadise/1.jpg",
      "/static/images/AlWazzan/6.jpg",
      "/static/images/Aprtment/5.jpg",
      "/static/images/ArtCenter/6.jpg",
      "/static/images/BelresheedDubaiOffice/9.jpg",
      "/static/images/BelresheedSharjahOffice/2.jpg",
      "/static/images/FitnessFirst/1.jpg",
      "/static/images/GentsSaloon/2.jpg",
      "/static/images/HamilAlmuskShop/1.jpg",
      "/static/images/JumeriahVilla/1.jpg",
      "/static/images/KSAVilla/10.jpg",
      "/static/images/MedicalCenter/1.jpg",
      "/static/images/MoroccanProject/7.jpg",
      "/static/images/OsamaVilla/7.jpg",
      "/static/images/PanamaDCC/11.jpg",
      "/static/images/Party21Sahara/1.jpg",
      "/static/images/Project3/3.jpg",
      "/static/images/Project5/3.jpg",
      "/static/images/Project6/4.jpg",
      "/static/images/Project7/2.jpg",
      "/static/images/Project8/3.jpg",
      "/static/images/Project9/5.jpg",
      "/static/images/ThaminaVilla/4.jpg",
      "/static/images/villaBarshaSouth/6.jpg",
      "/static/images/villaBarshaSouth/6.jpg"
    ],
    hover: [
      "/static/images/ADBank/Bank_View04.jpg",
      "/static/images/AjmanMajlis/47.JPG",
      "/static/images/AlWaleedParadise/3.jpg",
      "/static/images/AlWazzan/5.jpg",
      "/static/images/Aprtment/1.jpg",
      "/static/images/ArtCenter/10.jpg",
      "/static/images/BelresheedDubaiOffice/4.jpg",
      "/static/images/BelresheedSharjahOffice/7.jpg",
      "/static/images/FitnessFirst/10.jpg",
      "/static/images/GentsSaloon/1.jpg",
      "/static/images/HamilAlmuskShop/5.jpg",
      "/static/images/JumeriahVilla/4.jpg",
      "/static/images/KSAVilla/1.jpg",
      "/static/images/MedicalCenter/4.jpg",
      "/static/images/MoroccanProject/11.jpg",
      "/static/images/OsamaVilla/11.jpg",
      "/static/images/PanamaDCC/2.jpg",
      "/static/images/Party21Sahara/5.jpg",
      "/static/images/Project3/5.jpg",
      "/static/images/Project5/6.jpg",
      "/static/images/Project6/1.jpg",
      "/static/images/Project7/5.jpg",
      "/static/images/Project8/1.jpg",
      "/static/images/Project9/8.jpg",
      "/static/images/ThaminaVilla/9.jpg",
      "/static/images/villaBarshaSouth/21.jpg",
      "/static/images/villaBarshaSouth/21.jpg"
    ]
  }
;
